language: groovy

jdk:
- openjdk6

before_install:
- git submodule update --init --recursive
- sudo add-apt-repository -y ppa:groovy-dev/grails
- sudo apt-get update
- sudo apt-get install grails-2.1.1


script: mvn install -Dmaven.test.skip
